import sys
import numpy as np
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt, QTimer
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
from typing import List
from Wave import Wave

class ArrayElement:
    def __init__(self, position, wave:Wave, phase_shift=0, pattern_type='isotropic'):
        self.position = np.array(position)
        self.phase_shift = phase_shift
        self.wave = wave
        self.pattern_type = pattern_type
        
    def calculate_field(self, point,wave_velocity, time=0):
        """
        Calculates the Field effect due to each component of the wave generated by the array element
        """
        #Distance between element and point
        distance = np.linalg.norm(point - self.position)
        
        wave_numbers = []
        
        for component in self.wave.components:
            wave_number = 2*np.pi * (component.frequency / wave_velocity)
            wave_numbers.append(wave_number)
        
        # Calculate angle relative to element
        dx = point[0] - self.position[0]
        angle = np.arctan2(point[1] - self.position[1], dx)
            
        wave_fields = []
        for k in wave_numbers:
            wave_fields.append(np.exp(1j * (k * distance + self.phase_shift)) / max(distance, 0.1))
            
        if self.pattern_type == 'isotropic':
            pattern = 1.0
        else:  # sinc pattern
            u = k * dx * np.sin(angle)
            pattern = np.sinc(u / np.pi)
            
        total_wave_field = np.sum(wave_fields)    
        
        return total_wave_field  
  