classDiagram
    class PhasedArray {
        <<class>>
        - int num_elements
        - float element_spacing
        - str array_type (linear/curved)
        - list element_positions
        - list frequencies

        + set_geometry(type, parameters)
        + calculate_element_positions()
        + get_array_manifold()
    }

    class ArrayElement {
        <<class>>
        - float x_position
        - float y_position
        - float phase_shift
        - float amplitude

        + apply_phase_shift(shift)
        + set_amplitude(amp)
    }

    class BeamformingEngine {
        <<class>>
        - PhasedArray array
        - float steering_angle
        - float frequency

        + compute_phase_shifts()
        + calculate_beam_pattern()
        + steer_beam(angle)
        + generate_interference_map()
    }

    class ScenarioManager {
        <<class>>
        - dict predefined_scenarios

        + load_scenario(scenario_name)
        + save_scenario(scenario_config)
        + validate_scenario_parameters()
        + generate_scenario_template()
    }

    class VisualizationManager {
        <<class>>
        - BeamformingEngine engine

        + render_beam_profile()
        + plot_interference_map()
        + create_synchronized_views()
        + export_visualization()
    }

    class SimulationController {
        <<class>>
        - PhasedArray primary_array
        - list secondary_arrays
        - BeamformingEngine beam_engine
        - ScenarioManager scenario_manager
        - VisualizationManager visualization_manager

        + configure_system()
        + run_simulation()
        + add_phased_array()
        + update_parameters()
    }

    class FrequencyManager {
        <<class>>
        - list supported_frequencies
        - float current_frequency

        + set_frequency(freq)
        + generate_frequency_sweep()
        + validate_frequency_range()
    }

    class NoiseSimulator {
        <<class>>
        - float noise_level
        - str noise_type

        + add_gaussian_noise()
        + add_system_noise()
        + simulate_real_world_conditions()
    }

    SimulationController "1" *-- "1" PhasedArray : contains
    SimulationController "1" *-- "1" BeamformingEngine : manages
    SimulationController "1" *-- "1" ScenarioManager : uses
    SimulationController "1" *-- "1" VisualizationManager : controls

    PhasedArray "1" *-- "*" ArrayElement : composed of

    BeamformingEngine "1" -- "1" FrequencyManager : uses
    BeamformingEngine "1" -- "1" NoiseSimulator : incorporates

    VisualizationManager "1" -- "1" BeamformingEngine : renders results from